### ISSUE TITLE
Show a preview of the file

### ISSUE THREAD

**Issue by jancborchardt** [randomdeclutter/randomdeclutter#1]
Of course we need to show the preview of the file big enough. :)

@rullzer @icewind1991 so @xMartin checked the preview in the sidebar but it seemed to be very intertwined with the JS code. Is there a standard way to request the preview?

**Comment by rullzer** [comment]
For images etc there is a nice endpoint (won't work for PDF files etc as there we need dark javascript magic).

If you have the fileid/path you can use the preview endpoint https://github.com/nextcloud/server/blob/master/core/routes.php#L61

**Comment by jancborchardt** [comment]
@rullzer @xMartin any input on the work in progress at https://github.com/randomdeclutter/randomdeclutter/tree/fix-file-preview ?

**Comment by camilasan** [comment]
I think I introduced a few random errors but now there is a preview for the files that have one: https://github.com/randomdeclutter/randomdeclutter/tree/fix-file-preview

**Comment by jancborchardt** [comment]
Aaalright, this is done thanks to @camilasan! :) :tada:
